
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ombxfbwpqecgytwnhchc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tYnhmYndwcWVjZ3l0d25oY2hjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NjExNDcsImV4cCI6MjA1OTIzNzE0N30.BP9vAs_WH3tcxu8Qj13qIArKuoMU_T0EpsMwVY2_CYc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true
  }
});
